### PR TITLE
telegram.app

### PR DESCRIPTION
**Pull request by usercoder12**
..

### CODE REVIEW

**Comment by SAGARIKA-SHAH** [comment]
What's this?
Didn't get you.

**Comment by usercoder12** [comment]
idiot telegram pe aa

**Comment by usercoder12** [comment]
**Telegram pee aaaaaaaaa behen !!!!**

**Comment by SAGARIKA-SHAH** [comment]
Who??? There's nothing

**Comment by usercoder12** [comment]
tu kitni bhulkad h bee... bhul b gyi

**Comment by SAGARIKA-SHAH** [comment]
Utkarsh???

**Comment by usercoder12** [comment]
aisa aisa chizz aurr kon hi kr skta h ....chalo acha h tere ko naam toh yaad h

**Comment by SAGARIKA-SHAH** [comment]
So clever though!!!!
😂😂😂😂
How did u crack it?

**Comment by usercoder12** [comment]
behen tere ko yhi p baat krna h?ping me there

**Comment by SAGARIKA-SHAH** [comment]
U don't reply me thr

**Comment by usercoder12** [comment]
> 

chal be  ping me there

**Comment by usercoder12** [comment]
_???? kr_

**Comment by SAGARIKA-SHAH** [comment]
I'll do ruko abhi
Ek kaam hai vo finish karke
If yaad raha
Ek bar dilna yaad

**Comment by usercoder12** [comment]
waah behen ....fine I ll yaad dilao to u

**Pull request closed without merging**
